### ISSUE TITLE
Documentaion

### ISSUE THREAD

**Issue by KhadijaZahir** [KhadijaZahir/khadijaC2N3-Reenforcement#2]
Documentation sur :

- [x] Node.js

- [x] Npm

- [x] Node.sass

**Comment by youssefbm** [comment]
Jeter un coup d'oeil sur cette video : https://www.youtube.com/watch?v=yva2bj-lVRA

**Comment by KhadijaZahir** [comment]
Thanks a lot

Le lun. 24 févr. 2020 à 14:20, YoussefOuadid <notifications@github.com> a
écrit :

**Comment by KhadijaZahir** [comment]
finished party documentation

**Comment by youssefbm** [comment]
Well done
