### ISSUE TITLE
Coding mobile version

### ISSUE THREAD

**Issue by KhadijaZahir** [KhadijaZahir/khadijaC2N3-Reenforcement#3]
1.coding party html, and compiled Sass to css of this section by using Node sass.

- [x] using Node sass

- [x] using  sass and  Bem

- [ ] using javascript Jquery

1. Definition of done

- [x]  Designe de la page est conforme à celui de la maquette;

- [x] BEM appliqué;

- [ ] Code CSS réutilisable

- [ ] Code bien organisé et commenté;

- [ ] Explication claire et concise du code élaboré.

**Comment by KhadijaZahir** [comment]
finished mobile version

**Comment by youssefbm** [comment]
Bon travail
